# Generated by Django 3.2.6 on 2022-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_name', models.CharField(max_length=128)),
                ('name', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
