# Generated by Django 3.2.6 on 2022-07-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220713_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='shot_title',
            new_name='short_title',
        ),
    ]
