# Generated by Django 3.2.6 on 2022-07-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_shot_title_news_short_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.imgnews'),
        ),
    ]
