# Generated by Django 3.2.6 on 2022-07-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220713_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='imgnews',
            name='category_news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.news'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_image',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
    ]
