# Generated by Django 3.2.6 on 2022-07-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220713_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
