# Generated by Django 3.2.6 on 2022-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgnews',
            options={'verbose_name_plural': 'images for news'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='imgnews',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_image',
            field=models.ImageField(blank=True, upload_to='news_images'),
        ),
    ]
