# Generated by Django 3.2.6 on 2022-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20220814_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='person',
            field=models.CharField(blank=True, max_length=200, verbose_name='священослужитель(необезательно)'),
        ),
    ]
