# Generated by Django 3.2.6 on 2022-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_timetable_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='holiday',
            field=models.CharField(blank=True, choices=[('Y', 'Воскресный'), ('N', 'Не воскресный')], max_length=50, verbose_name='какой день'),
        ),
    ]
