# Generated by Django 3.2.6 on 2022-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_timetable_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=128, verbose_name='месяц')),
                ('abbot', models.CharField(max_length=128, verbose_name='настоятель')),
                ('phone', models.CharField(max_length=128, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
